creator/files/schema.py, creator/files/tests.py, creator/schema.py, creator/studies/models.py, creator/studies/tests.py, creator/urls.py, dev-requirements.txt, docs/uploads.rst, pytest.ini, requirements.txt, tests/data/manifest.txt, tests/test_query.py, tests/test_upload.py
Adds file upload functionality 
Fixes #9
=> ✨File upload

.circleci/config.yml, creator/files/factories.py, creator/files/management/commands/fakefiles.py, creator/files/schema.py, creator/schema.py, creator/studies/management/commands/fakestudies.py, creator/studies/models.py, creator/studies/schema.py, dev-requirements.txt, pytest.ini, tests/test_query.py, tests/test_upload.py
Add pytest-pep8 linter
Fixes #17
=> 🚨Add Pep8 linting

creator/settings.py, requirements.txt
Add the cors-headers package, closes #23
=> ✨ Add cors-headers package

creator/wsgi.py, manage.py, requirements.txt
=> ✨ Add dotenv

creator/files/factories.py
Fix the file factory by renaming 'batch' field to 'study'
=> 🐛 Rename batch to study

creator/files/schema.py, tests/test_upload.py
Return newly created file objects in createFile mutation closes #37
=> ♻️ Add file to createFile response

.circleci/config.yml, creator/settings.py, docker-compose.yml, requirements.txt
Switches to Postgres for database
- Change `settings.py`
- Change `docker-compose`
- Change CircleCI config
Fixes #38
=> 🐘 Switch to PostgreSQL

creator/files/models.py, creator/files/views.py, creator/urls.py, tests/conftest.py, tests/data/data.csv, tests/test_download.py
Add /download endpoint to download file given `study_id` and `file_id` from local or S3
closes #11
=> ✨ Add download endpoint

tests/test_download.py, tests/test_upload.py
Refactor `test_download` and `test_upload` to use upload_file fixture
=> ♻️ Refactor to use upload_file fixture

creator/files/models.py, creator/files/schema.py, tests/test_download.py
Add download field `downloadUrl` to GraphQL data response
closes #52
=> ✨ Add download field to GraphQL data response

creator/files/schema.py, tests/conftest.py, tests/test_download.py, tests/test_upload.py
Add authorization checks for file uploads
closes #54
=> ✨ Add upload authorization

creator/studies/schema.py
The study resolver was not receiving necessary arguments from kwargs to support pagination.
=> 🐛 Take kwargs on study resolver

creator/models.py
New manager to automatically plug in our custom fields for the `createsuperuser` function.
=> ✨ Add manager for custom user model

Dockerfile, Jenkinsfile, bin/entrypoint.sh, creator/settings.py, pytest.ini, requirements.txt
Adds Jenksfile to enable CI and deployment.
closes #16
=> 👷 Add Jenkinsfile

creator/files/views.py, creator/urls.py, tests/test_download.py
Add download URL option:
`download/study/<study_id>/file/<file_id>/version/<version_id>`
closes #58
=> ✨ Add version download endpoint

bin/entrypoint.sh, requirements.txt
Synchronize studies with dataservice on container start.
Fixes #75
=> ✨ Sync studies from dataservice

tests/conftest.py, tests/test_download.py, tests/test_query.py, tests/test_upload.py
In `prep-file` fixture:
1. Create one study
- authed = Ture -- study with ID `SD_00000000` (available to user_client)
- authed = False -- study with random ID
2. Upload one file to the study (default:`manifest.txt`)
3. Return `study_id`, `file_id`, `version_id`
closes #74
=> ♻️ Refactor test by adding prep-file fixture

creator/files/schema.py, tests/test_upload.py
Create a generic error message for failing to upload to S3
fixes #86
=> ✨ Upload error handling

creator/files/schema.py, creator/schema.py, tests/conftest.py, tests/test_query.py
File mutation on file name and file description.
Available for the  user who belongs to the study or is ADMIN
closes #84
=> ✨Add file mutation

docs/authentication.rst, docs/development/quickstart.rst, docs/model.rst
Add more information about user types and permissions
closes #85
=> 📝 Update documentation for permissions

creator/files/models.py, creator/files/schema.py, tests/test_download.py
Add download field downloadUrl to version object as GraphQL data response
closes #90
=> ✨Add version download field

creator/files/views.py, creator/urls.py
Combine function `download` and `download_latest` into one
closes #97
=> ♻️ Refactor download function

docs/uploads.rst
=> ♻️ Update documentation for Uploading with GraphQL

creator/files/views.py, tests/test_download.py
Only allow downloading if the user is an admin or is in the study group
closes #96
=> ✨Add download auth checking

creator/files/views.py, tests/test_download.py
Add error catching 404 for download error when the file no longer exists
Fixes #104
=> ♻️ Refactor download error

README.md, docker-compose.yml, docs/development/quickstart.rst
=> 🐳 Add service to kf-data-stack network

CHANGELOG.md
First release of the Kids First Study Creator.
Feature Emojis: ✨x17 ♻️x11 🐛x7 📝x5 🔧x5 ✨Addx4 🐳x1 👷x1 ✏️x1 🐘x1 🗃x1 🚨x1 📄x1 🎉x1
Feature Labels: [feature](https://api.github.com/repos/kids-first/kf-api-study-creator/labels/feature) x26 [refactor](https://api.github.com/repos/kids-first/kf-api-study-creator/labels/refactor) x13 [bug](https://api.github.com/repos/kids-first/kf-api-study-creator/labels/bug) x10 [documentation](https://api.github.com/repos/kids-first/kf-api-study-creator/labels/documentation) x8 [devops](https://api.github.com/repos/kids-first/kf-api-study-creator/labels/devops) x1
- (#108) 🐛 Fix public key problems - @dankolbman
- (#107) 🐳 Add service to kf-data-stack network - @znatty22
- (#106) ✨ JWT key validation - @dankolbman
- (#105) ♻️ Refactor download error - …
=>  Release 1.0.0

docs/uploads.rst
=> 📝Update uploads page

creator/files/schema.py, creator/schema.py, creator/studies/models.py, dev-requirements.txt, pytest.ini
Replace pep8 with pycode style.
Fixes #115
=> 🚨 Add pycodestyle

creator/files/schema.py, creator/schema.py, tests/test_mutation.py
Allows admin users to delete files.
Closes #123
=> ✨ Add deleteFile mutation

CHANGELOG.md
Small field addition to enable cache refreshes on the UI client.
Feature Emojis: ♻️x1
Feature Labels: [bug](https://api.github.com/repos/kids-first/kf-api-study-creator/labels/bug) x1
- (#153) ♻️ Return kf_id from delete file mutation - @dankolbman
=> 🏷 Release 1.2.1

creator/files/views.py
Should have been implemented in #182 but it wasn't.
=> 🐛 Use version file_name for downloads

creator/users/schema.py, tests/users/test_profile.py
Adds a query to get the request's authenticated user. Returns an error
if the request is unauthenticated or comes from a service.
=> ✨ Add myProfile query

creator/files/factories.py
Fake data are in use when doing `docker-compose up`.
- FileType field in file object is updated in its value options.
- New data fields in version object are added.
=> ♻️ Update fake data for files and versions

docs/authentication.rst, docs/authorization.rst, docs/index.rst
Revises the quickstart instructions to run in dev mode.
Adds more details about the authentication flow.
Adds detailed tables for `ADMIN` and `USER` role permissions.
=> 📝 Update docs

bin/dev_entrypoint.sh, creator/middleware.py
This automatically authenticates users as devadmin when running in
development mode. This allows users to upload files as the request is
associated with a real user object in the database now.
Fixes #196
=> 🔧 Authenticate requests as admin for development

docker-compose.dataservice.yml
Fix docker environment formatting by removing the spaces and quotes.
=> 🐳 Fix docker environment formatting

dev-requirements.txt
Have: moto==1.3.10 in dev-requirements.txt
=> ⬆️ Bump up moto to version 1.3.10

creator/projects/cavatica.py, creator/settings/development.py, creator/settings/production.py, creator/settings/testing.py, creator/studies/schema.py, docker-compose.yml, docs/development/quickstart.rst, requirements.txt, tests/projects/test_cavatica.py, tests/studies/test_create_study.py
=> ✨ Create new projects in Cavatica on study creation

creator/projects/cavatica.py, creator/projects/models.py
When creating a new study but no study name is given, study kfid would be used in naming the Cavatica projects.
=> 🐛 Fix project creation error with naming

creator/projects/cavatica.py, creator/projects/schema.py, creator/schema.py, tests/projects/test_cavatica_sync.py
Synchronize projects for all types, and update or create projects as needed and return changes.
Closes #236
=> ✨ Add sync projects mutation

creator/events/schema.py, creator/files/schema/__init__.py, creator/files/schema/file.py, creator/files/schema/version.py, creator/projects/schema.py, creator/schema.py, creator/studies/schema.py
This adds descriptions of all queries and mutations so that they are displayed within the graphiql viewer.
=> 📝 Add descriptions to all queries

creator/events/models.py, creator/studies/schema.py, tests/events/test_studies.py
Creates events when studies are updated or created.
Closes #239
=> ✨ Create events when studies are created

docs/cavatica.rst, docs/development/quickstart.rst, docs/index.rst
Adds information about settings and functionality of the Cavatica integration.
=> 📝 Add page about Cavatica integration

creator/projects/factories.py, creator/projects/schema.py, creator/schema.py, tests/projects/test_link_project.py
Adds a `linkProject` mutation to link a project to a study.
Closes #237
=> ✨ Add linkProject mutation

creator/projects/schema.py, creator/schema.py, tests/projects/test_link_project.py
Adds an `unlinkProject` mutation to remove a link between a study and a project.
Closes #257
=> ✨ Add unlinkProject mutation

creator/studies/schema.py
GraphQL error:
"Received not compatible datetime \"'2019-08-19T18:50:51.987799+00:00'\""
=> 🐛 Fix study createdAt date parsing

creator/schema.py, creator/studies/schema.py
Adds more documentation to study related entities.
=> 📝 Input docs

creator/projects/schema.py
Allows a study to be specified in the `allProjects` query to filter down to a particular study.
Providing an empty string will return all projects with no related study.
=> ✨ Add project study filter

CHANGELOG.md
Makes request timeouts configurable.
Feature Emojis: 🔧x1 ✨x1
Feature Labels: [feature](https://api.github.com/repos/kids-first/kf-api-study-creator/labels/feature) x2
- (#284) 🔧 Make requests timout configurable - @dankolbman
- (#283) ✨ Add project study filter - @dankolbman
=> 🏷 Release 1.6.1

creator/studies/schema.py
Allows users to update and set a study's bucket.
=> ✨ Make bucket modifiable

bin/entrypoint.sh
Loads credentials from S3 if the `DATABASE_SECRETS` variable is set in the environment.
=> 🔧 Load database creds from S3

bin/entrypoint.sh, creator/middleware.py, creator/settings/development.py, creator/settings/production.py, creator/settings/testing.py, creator/studies/bucketservice.py, creator/studies/schema.py, docs/bucketservice.rst, docs/index.rst, tests/studies/test_bucketservice.py
When a new study is created, the study-creator will call out the bucket service to setup a bucket for the study.
Closes #288
=> ✨ Integrate bucketservice

docs/dataservice.rst, docs/index.rst
Adds documentation on settings and features for Data Service integration.
Closes #282
=> 📝 Add page on Data Service settings

.circleci/config.yml, README.md, dev-requirements.txt
Code coverage reports are generated by pytest. 
These packages need to be installed (dev-requrrements)
pytest-cov==2.8.1
codecov==2.0.15
=> ✅ Add Codecov test as default pull request checking method

Dockerfile, bin/entrypoint.sh, creator/projects/cavatica.py, creator/settings/development.py, creator/settings/production.py, creator/settings/testing.py, docs/cavatica.rst, requirements.txt, tests/projects/fixtures.py, tests/projects/test_new_project.py, tests/studies/test_create_study.py
Attaches study's bucket as a volume in new Cavatica projects.
Still needs to be tested once the proper user accounts are set up.
Closes #233
=> ✨ Attach Cavatica volumes

CHANGELOG.md
Add user setting for email preference.
Setup Cavatica volumes for new projects.
Feature Emojis: ✨x2 ✅x1 🐛x1
Feature Labels: [feature](https://api.github.com/repos/kids-first/kf-api-study-creator/labels/feature) x2 [devops](https://api.github.com/repos/kids-first/kf-api-study-creator/labels/devops) x1 [bug](https://api.github.com/repos/kids-first/kf-api-study-creator/labels/bug) x1
- (#287) ✨ Attach Cavatica volumes - @dankolbman
- (#313) ✅ Add Codecov test as default pull request checking method - @XuTheBunny
- (#312) 🐛 Fix the user email/slack notify toggle mutation - @XuTheBunny
- (#311) ✨ Add email notification field - @dankolbman
=> 🏷 Release 1.7.2

creator/schema.py, creator/version_info.py, pytest.ini, tests/test_query.py
Adds status query to return current commit information about the study creator.
=> ✨ Add status query

Dockerfile, bin/dev_entrypoint.sh, bin/dev_worker.sh, bin/entrypoint.sh
Switches to using an alpine base to reduce image size.
=> 🐳 Use alpine image

Dockerfile
Installs `psql` in base image as a non-build requirement.
=> 🐳 Add postgresql client as persistent dep

README.md, docs/development/quickstart.rst, docs/index.rst, docs/uploads.rst
Update localhost port to 5002 for study-creator graphql interface
Add description for DEV and BETA role
=> 📝 Update localhost port to 5002 and add description for use roles

.coveragerc, creator/schema.py, creator/tasks.py, creator/version_info.py, docker-compose.yml, tests/tasks/test_setup_bucket_task.py, tests/tasks/test_setup_cavatica_task.py, tests/test_query.py, tests/test_version_info.py
This reports feature flags in the status query so that users may know what the service has been configured with.
=> ✨ Features in status

bin/dev_worker.sh, bin/worker.conf, creator/management/commands/schedule_jobs.py, creator/settings/development.py, creator/settings/production.py, creator/settings/testing.py, creator/studies/dataservice.py, creator/tasks.py, tests/studies/test_dataservice.py, tests/tasks/test_dataservice_sync_task.py
Adds sync task that will periodically run to align studies in the study creator with those in the dataservice.
Closes #332
=> ✨ Add Dataservice sync job

CHANGELOG.md
Adds task scheduler and status queries for exposing configuration.
Feature Emojis: ✨x7 🐳x3 📝x2 ⬆️x1 🔧x1
Feature Labels: [feature](https://api.github.com/repos/kids-first/kf-api-study-creator/labels/feature) x7 [devops](https://api.github.com/repos/kids-first/kf-api-study-creator/labels/devops) x3 [bug](https://api.github.com/repos/kids-first/kf-api-study-creator/labels/bug) x2 [documentation](https://api.github.com/repos/kids-first/kf-api-study-creator/labels/documentation) x2 [refactor](https://api.github.com/repos/kids-first/kf-api-study-creator/labels/refactor) x1
- (#336) ✨ Add Dataservice sync job - @dankolbman
- (#334) ✨ Import volume files - @dankolbman
- (#333) ✨ Add scheduled tasks - @dankolbman
- (#328) ✨ Allow users to specify and name research projects on creation - …
=> 🏷 Release 1.7.3

tests/test_query.py
Fixes version test for release tags.
=> 🚑 Version test hotfix

CHANGELOG.md
Hot fix to correct a test that fails for tagged branches.
Feature Emojis: 🚑x1
Feature Labels: [bug](https://api.github.com/repos/kids-first/kf-api-study-creator/labels/bug) x1
- (#338) 🚑 Version test hotfix - @dankolbman
=> 🏷 Release 1.7.4

CHANGELOG.md
Add bucket models and tags to documents.
Feature Emojis: ✨x5 🐛x1 ♻️x1
Feature Labels: [feature](https://api.github.com/repos/kids-first/kf-api-study-creator/labels/feature) x6 [bug](https://api.github.com/repos/kids-first/kf-api-study-creator/labels/bug) x1 [refactor](https://api.github.com/repos/kids-first/kf-api-study-creator/labels/refactor) x1
- (#354) 🐛 Allow files to be updated with no tags - @dankolbman
- (#353) ♻️ Refactor collaborator mutations - @dankolbman
- (#351) ✨ Bucket sync task - @dankolbman
- (#350) ✨ Add bucket models - @dankolbman
- (#345) ✨ Add collaborators to studies - @dankolbman
- (#342) ✨ Consolidate bucket service - @dankolbman
- (#344) ✨ Add tags field to file model and allow updating - @XuTheBunny
=> 🏷 Release 1.8.0

.github/workflows/dockerimage.yml, creator/settings/development.py
Builds images for master builds to push to Dockerhub.
=> 🐳 Build and push images to Dockerhub registry

docs/authorization.rst
Adds new permissions to documentation.
=> 📝 Update permission docs

creator/groups.py
Adds the `add_study` permission to admin users.
=> 🔒 Add create study permission

creator/groups.py, docs/authorization.rst
🔒 Add change study permission to Admin group
📝 Add change_study permission to Admin group in doc
=> 🔒 Add change study permission to Admin group

creator/studies/schema.py, tests/studies/test_create_study.py, tests/studies/test_update_study.py
Adds permission checks for creating and updating studies.
=> 🔒 Add permissions to study mutations

bin/dev_entrypoint.sh, creator/dev/urls.py, creator/dev/views.py, creator/management/commands/permission_tables.py, creator/management/commands/setup_test_user.py, creator/middleware.py, creator/settings/development.py, creator/settings/production.py, creator/settings/testing.py, creator/urls.py, dev-requirements.txt, docker-compose.yml, docs/conf.py, docs/development/dev_api.rst, docs/index.rst, tests/authentication/test_middleware.py, tests/dev/conftest.py, tests/dev/test_change_groups.py, tests/dev/test_reset_db.py, tests/files/test_downloads.py
Adds development endpoints if the `DEVELOPMENT_ENDPOINTS` setting is enabled:
- `__dev/reset-db/` - reset the database to base fake data
- `__dev/change-groups/groups=<>` change the permission groups of the `testuser`
Closes #366
=> ✨ Add development endpoints

creator/schema.py
Adds the development endpoints setting to the settings schema.
=> ✨ Add development endpoint to settings schema

bin/dev_entrypoint.sh
Setup the testuser before trying to create fake data which relies on the user existing
=> 🐛 Create test user before fake data

creator/files/schema/version.py
Allow investigators to upload new version
=> ♻️ Refactor the permission checking for uploading version

creator/buckets/factories.py, creator/files/factories.py, creator/files/management/commands/fakefiles.py, creator/projects/factories.py, creator/studies/factories.py, docker-compose.coordinator.yml
Makes files and version factories reproduce the same results when run through the Django command.
Adds tag fuzzer to generate fake tags on files.
=> ✨ Idempotent test files

CHANGELOG.md
Add study status columns
Feature Emojis: ✨x3
Feature Labels: [feature](https://api.github.com/repos/kids-first/kf-api-study-creator/labels/feature) x3
- (#392) ✨ Add phenotype status to study - @XuTheBunny
- (#391) ✨ Add ingestion status to study - @XuTheBunny
- (#388) ✨ Sequencing status - @dankolbman
=> 🏷 Release 1.10.0

bin/entrypoint.sh
Adds missing whitespace when checking for email settings.
=> 🐛 Fix email settings

creator/settings/development.py, creator/settings/production.py, creator/settings/testing.py
Uses the correct django settings for email encryption.
=> 🐛 Use proper email settings

creator/email/templates/base.html
Update Data Tracker logo used in emails to a png image.
=> 🖼 Update email picture

creator/settings/development.py, creator/settings/production.py, creator/settings/testing.py, requirements.txt
Uses the Django ses email backend to send email.
=> 📦 Use SES email backend

creator/email/templates/invite.html
Fixes typo in email templates.
=> ✏️ Correct typo in email

creator/email/templates/base.html
Shrinks email picture to take up less space.
=> 🖼 Shrink email header image

CHANGELOG.md
Add email invites for new and existing users.
- Emojis: 🖼 x2, ✏️ x1, 📦 x1, 🐛 x4, 🔧 x1, ✨ x3
- Categories: Other Changes x3, Fixes x5, Ops x1, Additions x3
- [#412](https://github.com/kids-first/kf-api-study-creator/pull/412) - 🖼 Shrink email header image - [20bd8398](https://github.com/kids-first/kf-api-study-creator/commit/20bd8398e8787a614374081d212666278a2ec49a) by [dankolbman](https://github.com/dankolbman)
- [#411](https://github.com/kids-first/kf-api-study-creator/pull/411) - ✏️ Correct typo in email - [9b3f6bdb](https://github.com/kids-first/kf-api-study-creator/commit/9b3f6bdb80fdd2d8d7fced16abaec363ef544c30) by [dankolbman](https://github.com/dankolbman)
- [#409](https://github.com/kids-first/kf-api-study-creator/pull/409) - 📦 Use SES email backend - …
=> 🏷 Release 1.11.0

bin/dev_worker.sh, bin/worker.conf, creator/management/commands/schedule_jobs.py, creator/slack.py, creator/tasks.py, tests/tasks/test_slack_notify_task.py
When has updates:
Slack job is monitored in configuration page:
Closes #403
=> ✨ Create daily Slack postings for study updates

creator/settings/development.py, creator/settings/production.py, creator/settings/testing.py, creator/slack.py, creator/studies/dataservice.py
Improves logging of tasks by:
- Enabling slack module logging
- Logging more details about dataservice syncing
- Fix warnings from missing timezone in query
=> 🔊Task logging

creator/management/commands/schedule_jobs.py, creator/slack.py, creator/tasks.py
Joins slack channels before trying to send daily notifications.
=> ♻️ Auto join Slack channels

creator/slack.py
Adds `utm_source` to urls in Slack pins.
=> 📈 Add utm tracking to slack pins

.github/workflows/gh_release.yml, CHANGELOG.md
- Emojis: 📈 x1, ♻️ x1, 🔊 x1, ⬆️ x1
- Categories: Additions x2, Other Changes x1, Ops x1
- [#420](https://github.com/kids-first/kf-api-study-creator/pull/420) - 📈 Add utm tracking to slack pins - [ab620d52](https://github.com/kids-first/kf-api-study-creator/commit/ab620d521558e9d1029964664449609b0879702c) by [dankolbman](https://github.com/dankolbman)
- [#419](https://github.com/kids-first/kf-api-study-creator/pull/419) - ♻️ Auto join Slack channels - [abd9b8a4](https://github.com/kids-first/kf-api-study-creator/commit/abd9b8a4dbec407497f00b0929e25a88ee73ca03) by [dankolbman](https://github.com/dankolbman)
- [#415](https://github.com/kids-first/kf-api-study-creator/pull/415) - 🔊 Task logging - [9761799d](https://github.com/kids-first/kf-api-study-creator/commit/9761799d4451717d5de31c4e5ef64 …
=> 🏷 Release 1.11.1

creator/studies/mutations.py
Close https://github.com/kids-first/kf-ui-data-tracker/issues/761
=> ♻️ Improve verbosity of collaborator events

CHANGELOG.md, release_maker_cfg.json
- Emojis: 🔥 x1, ♻️ x1
- Categories: Removals x1, Other Changes x1
- [#424](https://github.com/kids-first/kf-api-study-creator/pull/424) - 🔥 Remove default Cavatica projects for new studies - [958a1823](https://github.com/kids-first/kf-api-study-creator/commit/958a18234ca8066a531858a61a5d777c5382ba93) by [XuTheBunny](https://github.com/XuTheBunny)
- [#422](https://github.com/kids-first/kf-api-study-creator/pull/422) - ♻️ Improve verbosity of collaborator events - [4a387f40](https://github.com/kids-first/kf-api-study-creator/commit/4a387f40e7e2f7f36f1472fe33e1e45d74689972) by [XuTheBunny](https://github.com/XuTheBunny)
=> 🏷 Release 1.12.0

creator/studies/migrations/0019_add_through_relationship.py
Updates collaborator migration to keep existing users.
=> 🗃️ Patch collaborator mutation

creator/slack.py
Detailed events are listed underneath each file or collaborator updates.
Closes #427
=> ✨ Add file and collaborator details to slack notification

CHANGELOG.md
- Emojis: ✨ x2, 🗃️ x1
- Categories: Additions x2, Other Changes x1
- [#429](https://github.com/kids-first/kf-api-study-creator/pull/429) - ♻️  Separate update version permission to change meta and change status - [de1ed7ff](https://github.com/kids-first/kf-api-study-creator/commit/de1ed7ff89044c0375782f54897e29ba6d53b9f2) by [XuTheBunny](https://github.com/XuTheBunny)
- [#428](https://github.com/kids-first/kf-api-study-creator/pull/428) -   Add file and collaborator details to slack notification - [589ee225](https://github.com/kids-first/kf-api-study-creator/commit/589ee225dca8a21b5b4c0ad961394825ddaf91a1) by [XuTheBunny](https://github.com/XuTheBunny)
- [#426](https://github.com/kids-first/kf-api-study-creator/pull/426) - 🗃️  Patch collaborator mutation - …
=> 🏷 Release 1.13.0

creator/slack.py
=> ♻️ Shift slack messages timestamp to be US/Eastern timezone

creator/projects/schema.py, creator/referral_tokens/schema.py, creator/studies/nodes.py, tests/test_not_found.py
Adds general test for ensuring uniformity of not found responses.
=> ✅ Add test for unfound nodes

creator/buckets/mutations.py, creator/events/signals.py, creator/files/mutations/file.py, creator/management/commands/setup_test_user.py, creator/projects/cavatica.py, creator/projects/mutations.py, creator/referral_tokens/mutations.py, creator/slack.py, creator/studies/mutations.py, creator/users/schema.py
=> ♻️ Replace usernames in events with full names

CHANGELOG.md
- Emojis: 🐛 x2, ♻️ x3, ✅ x2, 🔧 x1, ✨ x1
- Categories: Fixes x2, Other Changes x6, Additions x1
- [#433](https://github.com/kids-first/kf-api-study-creator/pull/433) - 🐛 Fix file link in slack updates - [4266f2ff](https://github.com/kids-first/kf-api-study-creator/commit/4266f2ff97c984a944253bb6db24786081016ae6) by [XuTheBunny](https://github.com/XuTheBunny)
- [#446](https://github.com/kids-first/kf-api-study-creator/pull/446) - ♻️ Replace usernames in events with full names - [c9d459b5](https://github.com/kids-first/kf-api-study-creator/commit/c9d459b563052db4a461eafdf8043cef766de73a) by [XuTheBunny](https://github.com/XuTheBunny)
- [#444](https://github.com/kids-first/kf-api-study-creator/pull/444) - ✅ Add test for model strings - …
=> 🏷 Release 1.14.0

Dockerfile, bin/entrypoint.sh
Removes vault from entrypoint and docker image.
=> 🔥 Remove vault

creator/settings/development.py, creator/settings/production.py, creator/settings/testing.py
Adds SSL configuration setting to RQ config.
=> 🔧 Add SSL setting to RQ config

bin/entrypoint.sh, creator/settings/development.py, creator/settings/production.py, creator/settings/testing.py, creator/status/schema.py, requirements.txt
Fixes missing import.
Removes data service sync on task start (done by periodic job, now).
Corrects boolean from environment for SSL setting.
Upgrades rq dependencies.
=> 🔧 Dev Ops upgrades

creator/analyses/analyzer.py, creator/analyses/mutations.py, tests/analyses/test_create_analysis.py, tests/conftest.py
Resolves study through either the version or the root file of the version.
=> 🐛 Determine study from version or file

CHANGELOG.md
- Emojis: 🐛 x1, ♻️ x1, ✨ x2, 🔧 x2, 🔥 x1
- Categories: Fixes x1, Other Changes x3, Additions x2, Removals x1
- [#457](https://github.com/kids-first/kf-api-study-creator/pull/457) - 🐛 Determine study from version or file - [642c1aef](https://github.com/kids-first/kf-api-study-creator/commit/642c1aef4c47d0d37ee6147c8742affc59d31346) by [dankolbman](https://github.com/dankolbman)
- [#455](https://github.com/kids-first/kf-api-study-creator/pull/455) - ♻️ Refactor document upload flow - [f825f582](https://github.com/kids-first/kf-api-study-creator/commit/f825f582caede302a14493532bd5510a11905772) by [dankolbman](https://github.com/dankolbman)
- [#456](https://github.com/kids-first/kf-api-study-creator/pull/456) - ✨ Accept .xls file type for file analysis - …
=> 🏷 Release 1.14.1

CHANGELOG.md
- Emojis: 🐛 x1
- Categories: Fixes x1
- [#459](https://github.com/kids-first/kf-api-study-creator/pull/459) - 🐛 Check view_my_version permissions for downloads - [6a8cad5d](https://github.com/kids-first/kf-api-study-creator/commit/6a8cad5d42e505a72965157ef7b12782e366bd1b) by [dankolbman](https://github.com/dankolbman)
=> 🏷 Release 1.14.2

CHANGELOG.md
- Emojis: 📝 x1, 🔧 x1, 🐛 x1, ✨ x2
- Categories: Documentation x1, Other Changes x1, Fixes x1, Additions x2
- [#473](https://github.com/kids-first/kf-api-study-creator/pull/473) - 📝 Expand upload documentation - [f9927c5d](https://github.com/kids-first/kf-api-study-creator/commit/f9927c5db9ed352e70df14469f6e688225f467ee) by [dankolbman](https://github.com/dankolbman)
- [#471](https://github.com/kids-first/kf-api-study-creator/pull/471) - 🔧 Migrated to standard deployment - [cc742eae](https://github.com/kids-first/kf-api-study-creator/commit/cc742eaed19bb2d7b21f658affc9b8af58934ca2) by [alubneuski](https://github.com/alubneuski)
- [#470](https://github.com/kids-first/kf-api-study-creator/pull/470) - 🐛 Fix referral token exceptions - …
=> 🏷 Release 1.14.3

creator/settings/production.py
Get STAGE variable from the environment.
=> 🔧 Get stage from environment

CHANGELOG.md
- Emojis: 🔧 x1, ✨ x2
- Categories: Other Changes x1, Additions x2
- [#480](https://github.com/kids-first/kf-api-study-creator/pull/480) - 🔧 Get stage from environment - [1bc3dfd7](https://github.com/kids-first/kf-api-study-creator/commit/1bc3dfd7f23a840234c7a8e673981e145f86507d) by [dankolbman](https://github.com/dankolbman)
- [#475](https://github.com/kids-first/kf-api-study-creator/pull/475) - ✨ New expedited types - [e89a4ae5](https://github.com/kids-first/kf-api-study-creator/commit/e89a4ae525d1406144359a6236af668c22adc85f) by [dankolbman](https://github.com/dankolbman)
- [#472](https://github.com/kids-first/kf-api-study-creator/pull/472) - ✨ Add download extract config endpoint - [d845e21c](https://github.com/kids-first/kf-api-study-creator/commit/d845e21cb0d3226191ba88cadbff58b401af4 …
=> 🏷 Release 1.14.4

CHANGELOG.md
- Emojis: 🐛 x1
- Categories: Fixes x1
- [#483](https://github.com/kids-first/kf-api-study-creator/pull/483) - 🐛 Stringify before checking for printable chars - [eb43ec7c](https://github.com/kids-first/kf-api-study-creator/commit/eb43ec7c9fe9cc2e664c9077c5ca9b1243611090) by [dankolbman](https://github.com/dankolbman)
=> 🏷 Release 1.14.5

CHANGELOG.md
- Emojis: ✨ x2
- Categories: Additions x2
- [#494](https://github.com/kids-first/kf-api-study-creator/pull/494) - ✨ Add Genomic Workflow Output Manifest - [a9101a98](https://github.com/kids-first/kf-api-study-creator/commit/a9101a981ee0548eda6fcad4fba6906fcd070b67) by [znatty22](https://github.com/znatty22)
- [#482](https://github.com/kids-first/kf-api-study-creator/pull/482) - ✨ Job logs - [2bc60fd3](https://github.com/kids-first/kf-api-study-creator/commit/2bc60fd386d8c780f431e0b89b5e709920262d0d) by [dankolbman](https://github.com/dankolbman)
=> 🏷 Release 1.14.6

creator/middleware.py, creator/settings/development.py, creator/settings/production.py, creator/settings/testing.py, tests/authentication/test_middleware.py, tests/conftest.py, tests/users/test_create.py, tests/users/test_profile.py
Completely removes ego authentication middleware.
=> 🔥 Remove ego authentication

creator/events/schema.py
Resolve all of a user's studies before trying to filter events.
=> 🐛 Fix events query for non-admins

CHANGELOG.md
- Emojis: 🐛 x2, 🔥 x2, ⬆️ x1, ✨ x1
- Categories: Fixes x2, Removals x2, Ops x1, Additions x1
- [#515](https://github.com/kids-first/kf-api-study-creator/pull/515) - 🐛 Don't resolve downloadUrls if not enough info - [8dbae2a0](https://github.com/kids-first/kf-api-study-creator/commit/8dbae2a0691f978bf5c22b9b22ac7e064ca9c43d) by [dankolbman](https://github.com/dankolbman)
- [#514](https://github.com/kids-first/kf-api-study-creator/pull/514) - 🐛 Fix events query for non-admins - [9f2c9f81](https://github.com/kids-first/kf-api-study-creator/commit/9f2c9f817353218d175a658bb091c6199be7797b) by [dankolbman](https://github.com/dankolbman)
- [#511](https://github.com/kids-first/kf-api-study-creator/pull/511) - 🔥 Remove ego authentication - …
=> 🏷 Release 1.14.7

.env, creator/settings/development.py, creator/settings/features.py, creator/settings/production.py, creator/settings/testing.py, dev.env
Moves common feature settings into their file 
Closes #504
=> ♻️ Refactor settings

creator/wsgi.py
=> 🔥 Remove dotenv from WSGI

creator/decorators.py, creator/settings/production.py, requirements.txt, tests/studies/test_create_study.py
Install sentry for traceback reporting.
=> 📦 Install sentry

JenkinsfileWorker
=> 👷‍♂️ Updated module version

tests/studies/test_create_study.py
Resolves user by role to ensure the same user is used consistently throughout the test.
=> 🐛 Use same user throughout test

creator/status/banners/mutations.py, tests/status/test_banner_mutations.py, tests/status/test_banner_queries.py, tests/test_not_found.py
Forgotten functionality that should have been implemented in #517
=> ✨ Delete banners

creator/middleware.py, creator/settings/production.py, tests/test_middleware.py
Attaches user info to Sentry for better event tracking.
Closes #557
=> ✨ Attach users to Sentry

Dockerfile, Jenkinsfile
=> 🐳 Switch to python:3.8-slim-buster docker img

requirements.txt
=> ⬆️ Bump boto3 and requests

CHANGELOG.md
- Emojis: ✨ x1, 🔧 x2, 🐛 x3, ⬆️ x2, 🐳 x1, 💄 x1
- Categories: Additions x1, Other Changes x3, Fixes x3, Ops x3
- [#581](https://github.com/kids-first/kf-api-study-creator/pull/581) - ✨ Add investigator name to study - [7c147b2e](https://github.com/kids-first/kf-api-study-creator/commit/7c147b2e2da047961ca15380b8de58f9281557dd) by [dankolbman](https://github.com/dankolbman)
- [#580](https://github.com/kids-first/kf-api-study-creator/pull/580) - 🔧 Add flag to enabled/disable DR bucket creation - [428020b5](https://github.com/kids-first/kf-api-study-creator/commit/428020b5008050c2ed318176652c6b76d932bdd6) by [dankolbman](https://github.com/dankolbman)
- [#573](https://github.com/kids-first/kf-api-study-creator/pull/573) - 🔧 Add settings to status schema - …
=> 🏷 Release 1.15.0

CHANGELOG.md
- Emojis: 🐛 x1, 🔥 x1, ✨ x1
- Categories: Fixes x1, Removals x1, Additions x1
- [#586](https://github.com/kids-first/kf-api-study-creator/pull/586) - 🐛 Add missing import - [fdcd20a6](https://github.com/kids-first/kf-api-study-creator/commit/fdcd20a6891934b9df43774ea20fe4d3dbf69d23) by [dankolbman](https://github.com/dankolbman)
- [#587](https://github.com/kids-first/kf-api-study-creator/pull/587) - 🔥 Remove build_environments for worker - [7be9e360](https://github.com/kids-first/kf-api-study-creator/commit/7be9e3600b30b3bbe24c04b4f74d3bf5d1d60776) by [dankolbman](https://github.com/dankolbman)
- [#574](https://github.com/kids-first/kf-api-study-creator/pull/574) - ✨ Initial DataReview GraphQL API - [5903cbb8](https://github.com/kids-first/kf-api-study-creator/commit/5903cbb8233802c7bc4eb95 …
=> 🏷 Release 1.15.1

CHANGELOG.md
- Emojis: 👷 x1, ⬆️ x1, 🔧 x1
- Categories: Ops x2, Other Changes x1
- [#595](https://github.com/kids-first/kf-api-study-creator/pull/595) - 👷 Add new workflow for sentry releases - [ecddda23](https://github.com/kids-first/kf-api-study-creator/commit/ecddda234bee1710438997307ee5e32125051104) by [dankolbman](https://github.com/dankolbman)
- [#591](https://github.com/kids-first/kf-api-study-creator/pull/591) - ⬆️ Upgrade slack sdk - [5bd19f82](https://github.com/kids-first/kf-api-study-creator/commit/5bd19f82ff0968f06c83247ba161ea23c10a3084) by [dankolbman](https://github.com/dankolbman)
- [#594](https://github.com/kids-first/kf-api-study-creator/pull/594) - 🔧 Increase timeout for Cavatica tasks - [713c4c06](https://github.com/kids-first/kf-api-study-creator/commit/713c4c067fcbd55016f0498d557b …
=> 🏷 Release 1.15.2

creator/data_reviews/nodes.py
=> ✨ Make events in data_review node sortable with EventFilter

creator/ingest_runs/signals.py, creator/ingest_runs/tasks.py, creator/settings/features.py, tests/ingest_runs/test_ingest_runs_mutations.py, tests/ingest_runs/test_model.py, tests/ingest_runs/test_signals.py, tests/ingest_runs/test_tasks.py
Increase code coverage on the ingest-app branch so that we can merge it into master. Add a `FEAT_INGEST_GENOMIC_WORKFLOW_OUTPUTS` feature flag and associated test which allows for the ingestion of GWO to be toggled on/off.
=> ✅ Tests for ingest-app branch and ingest GWO feature flag

CHANGELOG.md
- Emojis: ✨ x1
- Categories: Additions x1
- [#612](https://github.com/kids-first/kf-api-study-creator/pull/612) - ✨ Save services as users - [f67bd173](https://github.com/kids-first/kf-api-study-creator/commit/f67bd17393a5618f9f8fbad4235c5b3d3cd364a6) by [dankolbman](https://github.com/dankolbman)
=> 🏷 Release 1.17.0

CHANGELOG.md
- Emojis: 🐛 x1, ✨ x2, ⬆️ x1
- Categories: Fixes x1, Additions x2, Ops x1
- [#621](https://github.com/kids-first/kf-api-study-creator/pull/621) - 🐛 Don't refetch tokens every request - [72f4706f](https://github.com/kids-first/kf-api-study-creator/commit/72f4706fd92a0f70f8957252648a800192fad998) by [dankolbman](https://github.com/dankolbman)
- [#613](https://github.com/kids-first/kf-api-study-creator/pull/613) - ✨ Validation GraphQL API - [2ef7a6ee](https://github.com/kids-first/kf-api-study-creator/commit/2ef7a6ee673b0682ab69b01d2988adeef814af24) by [znatty22](https://github.com/znatty22)
- [#498](https://github.com/kids-first/kf-api-study-creator/pull/498) - ✨ New ingest runs app - [ef282950](https://github.com/kids-first/kf-api-study-creator/commit/ef282950fc007292c5458175bec2cc72f7c3fd35 …
=> 🏷 Release 1.17.1

creator/ingest_runs/common/model.py, tests/ingest_runs/test_common.py
Closes #654 
Gives the parent class `IngestProcess` a `study` attribute which yields `NotImplementedError` when accessed, and adds a test to check this. Also applies black formatting to the relevant files.
=> ♻️ Add study attribute to IngestProcess

creator/files/models.py, creator/ingest_runs/models/validation_run.py, requirements.txt, tests/conftest.py, tests/files/test_upload.py
Bump Django version to deal with regression regarding path elements in file names.
=> ⬆️ Bump Django version to fix regression

creator/ingest_runs/genomic_data_loader.py
Closes #663 
When running tests we get a bunch of `SettingWithCopyWarning` notices from pandas.
`GenomicDataLoader` is refactored to get rid of these and avoid modifying copies of DataFrames.
=> ♻️ Fix pandas indexing warnings

creator/studies/nodes.py, creator/studies/schema.py, tests/studies/test_study_queries.py
Closes #520 
Add a new parameter to the `allStudies` query to allow for sorting based on the time of the last created Version.
=> ✨ Sort studies by last active

creator/events/models.py, creator/organizations/mutations.py, creator/studies/mutations.py, tests/organizations/test_add_remove_member.py, tests/studies/test_transfer_study.py
✨ Add mutation to transfer study to another organization
Closes #657
✨ Add mutation to add member to an organization
✨ Add mutation to remove member from an organization
Closes #656
=> ✨ Add mutation to transfer study to another organization

CHANGELOG.md
- Emojis: 🔧 x1, ♻️ x8, 🐛 x2, ✨ x9, 👷 x1, ⬆️ x4, ? x1, 📝 x1, 🔊 x1
- Categories: Additions x10, Documentation x1, Fixes x2, Ops x5, Other Changes x10
- [#692](https://github.com/kids-first/kf-api-study-creator/pull/692) - 🔧 Increase max number of relay connections - [b626c021](https://github.com/kids-first/kf-api-study-creator/commit/b626c0214861652426be6e0fc82f9262d8384c64) by [dankolbman](https://github.com/dankolbman)
- [#687](https://github.com/kids-first/kf-api-study-creator/pull/687) - ♻️ Remove obsolete file types - [5e718da8](https://github.com/kids-first/kf-api-study-creator/commit/5e718da86d41fbcad56ce25f299c8961d140b09d) by [gsantia](https://github.com/gsantia)
- [#690](https://github.com/kids-first/kf-api-study-creator/pull/690) - 🐛 Fix order of organization migrations - …
=> 🏷 Release 1.18.0

CHANGELOG.md
- Emojis: 🔧 x1
- Categories: Other Changes x1
- [#696](https://github.com/kids-first/kf-api-study-creator/pull/696) - 🔧 Run scheduler without supervisor - [5e652a7d](https://github.com/kids-first/kf-api-study-creator/commit/5e652a7d8fe8401423b49551830afa12dd769add) by [dankolbman](https://github.com/dankolbman)
=> 🏷 Release 1.18.1

creator/slack.py
Closes #686 
When Slack messages pass 50 blocks, an error occurs. If we are about to send a message with over 50 blocks, instead send just the 49 last blocks and append an additional block telling the user about this truncation.
=> ♻️ Limit length of Slack notifications

CHANGELOG.md
- Emojis: ♻️ x2, ✨ x2
- Categories: Additions x2, Other Changes x2
- [#705](https://github.com/kids-first/kf-api-study-creator/pull/705) - ♻️ Relax required columns in file types - [3f81405f](https://github.com/kids-first/kf-api-study-creator/commit/3f81405f76791ca398c03347e91a79cb7ab13bb8) by [znatty22](https://github.com/znatty22)
- [#693](https://github.com/kids-first/kf-api-study-creator/pull/693) - ✨ Add mutations to link/unlink templates to/from studies - [d159335c](https://github.com/kids-first/kf-api-study-creator/commit/d159335c0ec92c475a8816b4b82bda5da906a3b5) by [gsantia](https://github.com/gsantia)
- [#698](https://github.com/kids-first/kf-api-study-creator/pull/698) - ♻️ Limit length of Slack notifications - [6478978e](https://github.com/kids-first/kf-api-study-creator/commit/ …
=> 🏷 Release 1.18.2

creator/data_templates/factories.py, creator/data_templates/field_definitions_schema.py, creator/data_templates/models.py, requirements.txt, tests/data_templates/test_field_definitions.py, tests/data_templates/test_template_version_mutations.py
Closes #679 
Adds validation for template field definitions via a marshmallow schema
=> ✨ Template Field Definition Validation

creator/data_templates/field_definitions_schema.py, creator/data_templates/models.py, creator/data_templates/packaging.py, creator/data_templates/views.py, creator/urls.py, requirements.txt, tests/data_templates/test_download_templates.py, tests/data_templates/test_field_definitions.py, tests/data_templates/test_package_templates.py, tests/data_templates/test_template_models.py
Closes #677 
Download study templates as an excel workbook or zip file
```
/download/templates/SD_ME0WME0W
/download/templates/SD_ME0WME0W?template_version_ids=TV_001,TV002
/download/templates/SD_ME0WME0W?file_format=zip
/download/templates/SD_ME0WME0W?file_format=zip&template_version_ids=TV_001,TV002
```
=> ✨ Download study templates

CHANGELOG.md
- Emojis: ✨ x5, 🛠 x1
- Categories: Additions x5, Other Changes x1
- [#711](https://github.com/kids-first/kf-api-study-creator/pull/711) - ✨ Upload field definitions - [602e042b](https://github.com/kids-first/kf-api-study-creator/commit/602e042b9738de764726d28f862c2f2d18b64037) by [znatty22](https://github.com/znatty22)
- [#715](https://github.com/kids-first/kf-api-study-creator/pull/715) - 🛠 add 'sentry-trace' to CORS allowed headers - [3fb7a8aa](https://github.com/kids-first/kf-api-study-creator/commit/3fb7a8aae749b68d33be2f26bca06c62da59da2b) by [jgnieuwhof](https://github.com/jgnieuwhof)
- [#703](https://github.com/kids-first/kf-api-study-creator/pull/703) - ✨ Add User organization filter - [359bd73c](https://github.com/kids-first/kf-api-study-creator/commit/359bd73cf08d78e6dfff00558105 …
=> 🏷 Release 1.19.0

requirements.txt
Upgrade the version of the Sentry SDK.
=> ⬆️ Upgrade sentry

CHANGELOG.md
- Emojis: 🐛 x1, 🔊 x1, ⬆️ x1
- Categories: Additions x1, Fixes x1, Ops x1
- [#720](https://github.com/kids-first/kf-api-study-creator/pull/720) - 🐛 Increase worker task and container size - [f0a2e2b8](https://github.com/kids-first/kf-api-study-creator/commit/f0a2e2b869ce21222b5cbc2d261b4b6eee10492d) by [blackdenc](https://github.com/blackdenc)
- [#726](https://github.com/kids-first/kf-api-study-creator/pull/726) - 🔊 Configure TaskLogger directly - [df99e512](https://github.com/kids-first/kf-api-study-creator/commit/df99e512adf4fa36053088d61ff2aa3ae67efb4a) by [dankolbman](https://github.com/dankolbman)
- [#721](https://github.com/kids-first/kf-api-study-creator/pull/721) - ⬆️ Upgrade sentry - [ee286d53](https://github.com/kids-first/kf-api-study-creator/commit/ee286d53112d2099d9dc0d65b98071 …
=> 🏷 Release 1.19.1

CHANGELOG.md
- Emojis: 🐛 x1
- Categories: Fixes x1
- [#731](https://github.com/kids-first/kf-api-study-creator/pull/731) - 🐛 Permit all non-machine roles to view and list templates - [027f223d](https://github.com/kids-first/kf-api-study-creator/commit/027f223dae8b1ccf39517f2115991dd00ab3afb9) by [znatty22](https://github.com/znatty22)
=> 🏷 Release 1.19.2

creator/data_templates/management/commands/faketemplates.py, tests/data_templates/test_commands.py
Templates were not being deleted when user passed --delete option
=> 🐛 Delete templates in faketemplates cmd if flag is given

CHANGELOG.md
- Emojis: 🐛 x1, ✨ x1, 💬 x1
- Categories: Additions x1, Fixes x2
- [#739](https://github.com/kids-first/kf-api-study-creator/pull/739) - 🐛 Delete templates in faketemplates cmd if flag is given - [01317104](https://github.com/kids-first/kf-api-study-creator/commit/01317104c838bedbbed5c6df2870cb54c02e1a9d) by [znatty22](https://github.com/znatty22)
- [#730](https://github.com/kids-first/kf-api-study-creator/pull/730) - ✨ Add endpoint to download template versions - [4b6c1584](https://github.com/kids-first/kf-api-study-creator/commit/4b6c1584ea260b2f6fbe26c17e087fb9cf0d6707) by [gsantia](https://github.com/gsantia)
- [#738](https://github.com/kids-first/kf-api-study-creator/pull/738) - 💬 Add user to template event description - [dcda26cc](https://github.com/kids-first/kf-api-study-creator/com …
=> 🏷 Release 1.19.4

creator/data_templates/factories.py, creator/data_templates/models.py, tests/data_templates/test_template_models.py
=> 🐛 Fix processing of missing value list

CHANGELOG.md
- Emojis: 🐛 x1, ♻️ x1
- Categories: Fixes x1, Other Changes x1
- [#746](https://github.com/kids-first/kf-api-study-creator/pull/746) - 🐛 Fix processing of missing value list - [ffeb690b](https://github.com/kids-first/kf-api-study-creator/commit/ffeb690ba27b62469c812fd866cf08ef80737dbf) by [znatty22](https://github.com/znatty22)
- [#742](https://github.com/kids-first/kf-api-study-creator/pull/742) - ♻️ Refactor validation to use templates - [a5c722e8](https://github.com/kids-first/kf-api-study-creator/commit/a5c722e8409f584f5289c00937870e8a2e9172b9) by [znatty22](https://github.com/znatty22)
=> 🏷 Release 1.19.5

CHANGELOG.md
- Emojis: 🔊 x1, ♻️ x2, 🐛 x1
- Categories: Additions x1, Fixes x1, Other Changes x2
- [#761](https://github.com/kids-first/kf-api-study-creator/pull/761) - 🔊 Configure release task logging directly - [7ecbb638](https://github.com/kids-first/kf-api-study-creator/commit/7ecbb63805bc2d1ba0e10f4b0151735aa56bd586) by [znatty22](https://github.com/znatty22)
- [#753](https://github.com/kids-first/kf-api-study-creator/pull/753) - ♻️ Adjust validation rules and report - [cdabec75](https://github.com/kids-first/kf-api-study-creator/commit/cdabec7564f3b61e862db7e0f1dd9bb3ab8c9ba0) by [znatty22](https://github.com/znatty22)
- [#741](https://github.com/kids-first/kf-api-study-creator/pull/741) - ♻️ Restore old general file types and add new ones - …
=> 🏷 Release 1.19.6

CHANGELOG.md
- Emojis: 🐛 x2, ♻️ x1
- Categories: Fixes x2, Other Changes x1
- [#768](https://github.com/kids-first/kf-api-study-creator/pull/768) - 🐛 Fix API logging - [b07e9b96](https://github.com/kids-first/kf-api-study-creator/commit/b07e9b96f74208844395cb0de3aefe509704ca53) by [znatty22](https://github.com/znatty22)
- [#767](https://github.com/kids-first/kf-api-study-creator/pull/767) - 🐛  Fix writing of job logs in local development - [d078b8eb](https://github.com/kids-first/kf-api-study-creator/commit/d078b8eb597e62672f2720d146dd868d03caebb9) by [znatty22](https://github.com/znatty22)
- [#763](https://github.com/kids-first/kf-api-study-creator/pull/763) - ♻️ Omit Content-Length header in download validation report - [f61c0e80](https://github.com/kids-first/kf-api-study-creator/commit/f61c0e8078d0 …
=> 🏷 Release 1.19.7

CHANGELOG.md
- Emojis: 🐛 x1, 🔥 x1
- Categories: Removals x1, Fixes x1
- [#772](https://github.com/kids-first/kf-api-study-creator/pull/772) - 🐛 Fix slack notifications - [4d956184](https://github.com/kids-first/kf-api-study-creator/commit/4d95618413662676006ad967e5d5dc2671e72b3c) by [znatty22](https://github.com/znatty22)
- [#774](https://github.com/kids-first/kf-api-study-creator/pull/774) - 🔥 Remove sync job with old release coordinator - [7b445e8c](https://github.com/kids-first/kf-api-study-creator/commit/7b445e8cfc7d5c1e44a4777e459189077248bbb7) by [znatty22](https://github.com/znatty22)
=> 🏷 Release 1.19.8

dev-requirements.txt
=> 📌 Pin docutils<0.18

creator/buckets/buckets.py
=> 🐛 Use proper bucket arn in bucket inventory configuration

creator/data_templates/views.py
=> 🛠 Expose content-disposition header in download template reqs

CHANGELOG.md
- Emojis: 🛠 x1, ✨ x1, 🐛 x1
- Categories: Additions x1, Fixes x1, Other Changes x1
- [#804](https://github.com/kids-first/kf-api-study-creator/pull/804) - 🛠 Expose content-disposition header in download template reqs - [ff6360a0](https://github.com/kids-first/kf-api-study-creator/commit/ff6360a084244b50101dadd0d57559f1762f0f5b) by [znatty22](https://github.com/znatty22)
- [#789](https://github.com/kids-first/kf-api-study-creator/pull/789) - ✨ Add short_code, domain, and program to Study - [c13c6567](https://github.com/kids-first/kf-api-study-creator/commit/c13c6567af4927ff3da2effeedbd18f2b8113ef7) by [gsantia](https://github.com/gsantia)
- [#799](https://github.com/kids-first/kf-api-study-creator/pull/799) - 🐛 Fix study sync f-string - …
=> 🏷 Release 1.21.0

CHANGELOG.md
- Emojis: 🗃 x1
- Categories: Other Changes x1
- [#805](https://github.com/kids-first/kf-api-study-creator/pull/805) - 🗃 Fix study domains from prev domain migration - [ef79bea6](https://github.com/kids-first/kf-api-study-creator/commit/ef79bea684b231c22493a3e44a4d67b099dd01fb) by [znatty22](https://github.com/znatty22)
=> 🏷 Release 1.21.1

CHANGELOG.md
- Emojis: ? x1, ♻️ x1, ⬆️ x1
- Categories: Additions x1, Ops x1, Other Changes x1
- [#853](https://github.com/kids-first/kf-api-study-creator/pull/853) -  :bug: Sync all studies in dataservice - [ba62b369](https://github.com/kids-first/kf-api-study-creator/commit/ba62b369e6464259ea92dbb9ba49876513f37fba) by [znatty22](https://github.com/znatty22)
- [#811](https://github.com/kids-first/kf-api-study-creator/pull/811) - ♻️ Refactor referral token mutation and event messages - [c8558574](https://github.com/kids-first/kf-api-study-creator/commit/c85585745fc68ccdcb56530bc032c0bb94da29cc) by [XuTheBunny](https://github.com/XuTheBunny)
- [#810](https://github.com/kids-first/kf-api-study-creator/pull/810) - ⬆️ Security upgrade django from 2.2.24 to 2.2.26 - …
=> 🏷 Release 1.22.0
