kids-first/kf-api-study-creator

creator/urls.py

Remove csrf checks from the /graphql endpoint closes #26

🔧 Exempt csrf from graphql endpoint

---

Dockerfile
bin/dev_entrypoint.sh
bin/entrypoint.sh
docker-compose.yml
docs/development/quickstart.rst
docs/index.rst

Adds a `dev` stage to the dockerfile which will install the dev requirements and use the dev entrypoint.
User may specify if they want `DATASERVICE` or `FAKE` data by using the `PRELOAD_DATA` environment variable in the docker-compose.
Fixes #45

♻️ Add dev stage to Dockerfile

---

creator/files/schema.py
creator/settings.py
tests/test_upload.py

Set default max file size as 1G for uploading, expecting GraphQL error message.
closes #21

✨ Set max upload file size

---

creator/files/schema.py
tests/test_query.py

Add three permission checking to allFiles query
- If the user is unauthed: should return no files
- If the user is authed but not ADMIN: should only return the files under the studies belonging to the user
- If the user is ADMIN: should return all files
- 
closes #62

✨ Add permission checking to allFiles query

---

creator/files/schema.py
tests/test_query.py

Add three permission checking to allVersions query
- If the user is USER, only return the file versions from the studies which the user belongs to
- If the user is ADMIN, return all file versions
- If the user is unauthed, return no file versions
closes #63

✨ Add permission checking to allVersions query

---

requirements.txt

Get's rid of the wheel deprecation warnings when loading psycopg2.

🐛 Installs psycopg2-binary

---

bin/dev_entrypoint.sh

Avoids unique constraint error when the service is recreated using the same database.

🐛 Don't create admin if already exists

---

creator/middleware.py
creator/settings/development.py
creator/settings/production.py
creator/settings/testing.py

Authenticates all requests with an admin user when running with the development settings.
Fixes #70

🔧 Bypass authentication in development

---

creator/urls.py

Returns the GraphiQL view on the root page to make ALB health checks pass.

🔧 Display graphiql on site root

---

creator/settings/development.py
creator/settings/production.py
creator/settings/testing.py

Updated ` FILE_MAX_SIZE` to 2^29 (537M) for `production`, `development` and `testing`

♻️ Increate upload file size limitation to 537M

---

docker-compose.yml

Uses the `PRELOAD_DATA` environment variable when running docker-compose.

🔧 Load PRELOAD_DATA from env

---

creator/files/views.py
tests/data/name with spaces.txt
tests/test_download.py

When downloading, the file name with spaces in it will be reformated as `XXX%20XXX.txt`
closes #95

♻️ Reformat file name

---

creator/files/views.py
tests/test_download.py

Disallows downloads with correct file and object ids, but invalid study ids.
Fixes #126

✨ Require study id in download to be valid

---

creator/files/schema.py
creator/schema.py
docs/downloads.rst
tests/test_mutation.py

Allows signed urls to be generated with a graphQL mutation.
Closes #127

✨ Add mutation to make signed url

---

creator/files/admin.py
creator/studies/admin.py
creator/urls.py

Removes the admin route and adding of models to admin.
Closes #119

🔥 Remove django admin

---

creator/middleware.py
tests/authentication/test_middleware.py

Caches the json encoded key in the cache so that it may be used to validate JWTs without having to be retrieved from auth0 in every request.
Fixes #131

♻️ Cache JWKS for future validation

---

creator/middleware.py
creator/settings/development.py
creator/settings/production.py
creator/settings/testing.py
tests/authentication/test_middleware.py
tests/conftest.py
tests/test_download.py
tests/test_mutation.py

Authenticates tokens with `client-credentials` grant type and correct scope as an ADMIN user.
We may wish to revisit this if we refactor our auth to make better use of permissions.
Closes #110

✨ Service token auth

---

creator/files/views.py
tests/test_download.py

Safari will not infer file types from extensions and will instead use the Content-Type alone to determine the file extension thus resulting in all files being downloaded with `.html` appended. This specifies the content type as `application/octet-stream` so that Safari will not try to guess from the header.
Fixes #144

🐛 Add Content-Type header to downloads

---

creator/files/views.py
tests/test_dev_tokens.py
tests/test_download.py

Encodes the `filename` with utf-8 for the content disposition header.
Fixes #141

🐛 Use utf-8 encoding for Content-Disposition

---

creator/files/views.py
tests/test_dev_tokens.py
tests/test_download.py

Returns 401 along with 'Not authorized to download the file' when invalid or no credentials are supplied to the download endpoint.
Fixes #148

🐛 Return 401 when not authed for download

---

.circleci/config.yml

Ignores gh-pages in circle which will fail due to not having any of the source code in it.

🙈 Ignore gh-pages in CircleCI

---

creator/files/schema.py

The UI needs to know what token was deleted so that it may remove it from the interface.

♻️ Return name of token from mutation

---

creator/files/schema.py

The UI needs to know what file has been deleted as a result of the `deleteFile` mutation.

♻️ Return kf_id from delete file mutation

---

creator/files/schema.py
creator/schema.py
docs/uploads.rst
tests/conftest.py
tests/test_upload.py

This PR allows uploads of new versions of files by providing an additional but optional parameter `fileId` to the `createFile` mutation.
This will add the new Object of the File specified by the `fileId`, if it exists.
Closes #155

✨ Version uploads

---

creator/files/schema.py
creator/files/schema/__init__.py
creator/files/schema/file.py
creator/files/schema/version.py
creator/schema.py
tests/conftest.py
tests/files/test_upload.py

This refactors the schema layout for the file app schemas and adds a new `createVersion` mutation to allow more individualized uploading specific to either versions or files.
This also enforces required fields for both mutations:
`createFile` - Required `description`, `fileType`, `studyId`
`createVersion` - Required `description`, `fileId`
Fixes #169 
Fixes #159

♻️ Split file and version upload mutations

---

creator/files/schema/version.py

Adds file kf_id filter to the `allVersions` query to allow filtering versions by their parent file.
Closes #213

✨ Add filter by file kf_id to allVersions

---

docker-compose.yml

Sets both study-creator's and dataservice's postgres containers to use a common 11.1 version of postgres to eliminate the need to pull multiple containers for postgres when running a compose file.

🐳 Use common postgres versions for containers

---

bin/dev_entrypoint.sh

Fixes bug where running docker-compose up would cause an error when restarting the web service when the database was already initialized, causing a duplicate key error for the admin user.

🐛 Don't try to recreate dev user

---

creator/events/schema.py
tests/events/test_event_auth.py

This renames filter fields explicitly so that there are no awkward
underscores stuck in filter fields that result from django's
related-field referencing syntax.

♻️ Rename event filter arguments

---

creator/settings/development.py
creator/settings/production.py
creator/settings/testing.py
docker-compose.yml
tests/projects/test_cavatica.py
tests/projects/test_cavatica_sync.py
tests/studies/test_create_study.py

This sets tokens to None and simply passes the token environment values
through the compose file instead of setting defaults. This allows the
Cavatica features to be skipped in development mode instead of
incorrectly trying to use default values.

🔧 Remove default Cavatica token settings

---

creator/projects/cavatica.py

This fixes the bug where times cannot be compared because Cavatica does not return timezones on its datetimes. This also silences warning from the database which expects times to have timezones.

🐛 Make Cavatica times timezone aware

---

creator/studies/schema.py
tests/studies/test_create_study.py
tests/studies/test_update_study.py

This adds the `releaseDate` to the `StudyInput` so that it may be set during study creation and updates.
It also fixes an issue where the non-dataservice fields were not being saved to studies and adds some more tests to help check this doesn't regress.

🐛 Add release date to mutations

---

creator/projects/schema.py
creator/schema.py
pytest.ini
tests/projects/conftest.py
tests/projects/test_cavatica.py
tests/projects/test_cavatica_sync.py
tests/projects/test_new_project.py

Allows the creation of new projects for a given study.
Does not allow creating new projects for a study where another project with the same workflow already exists.
Closes #275

✨ Add createProject mutation

---

creator/projects/schema.py
tests/projects/test_new_project.py

Updates the `createProject` mutation to explicitly take a global ID type for the study rather than a generic string/kf_id.

♻️ Use ID type for study argument in createProject mutation

---

creator/projects/cavatica.py
creator/studies/schema.py

- Fixes warning where Projects were created with datetimes with no timezone
- Prevents serialization failure on study update due to bad datetime format from dataservice
- Updates an existing study's attributes rather than create a new study with the attributes.

🐛 Fix datetime issues

---

creator/middleware.py
creator/settings/development.py
creator/settings/production.py
creator/settings/testing.py
creator/users/schema.py
docker-compose.yml
docs/development/quickstart.rst
tests/users/test_profile.py

This allows a user's roles and groups to be specified by `USER_ROLES` and `USER_GROUPS` when running the API with development settings.
It also returns the groups and roles in the  user's profile so that the frontend may be made aware of these modifications that were made server side.
Closes #277

✨ Add overrides for user's roles and groups

---

CHANGELOG.md

Introduces study creation and Cavatica project automation features.
Feature Emojis: ✨x20 🐛x7 📝x3 ⬆️x3 ♻️x2 🔧x2 🐳x2 👷x1 🗃x1 🔥
Feature Labels: [feature](https://api.github.com/repos/kids-first/kf-api-study-creator/labels/feature) x19 [bug](https://api.github.com/repos/kids-first/kf-api-study-creator/labels/bug) x11 [refactor](https://api.github.com/repos/kids-first/kf-api-study-creator/labels/refactor) x8 [devops](https://api.github.com/repos/kids-first/kf-api-study-creator/labels/devops) x4 [documentation](https://api.github.com/repos/kids-first/kf-api-study-creator/labels/documentation) x3
- (#280) ✨ Add overrides for user's roles and groups - @dankolbman
- (#278) 🐛 Fix datetime issues - @dankolbman
- (#279) ♻️ Use ID type for study argument in createProject mutation - @dankolbman
- …

🏷 Release 1.6.0

---

creator/settings/development.py
creator/settings/production.py
creator/settings/testing.py

Makes the requests timeout configurable and bumps its default value to 30s.

🔧 Make requests timout configurable

---

creator/events/schema.py
tests/events/test_event_auth.py

Renames the `createdAt_Gt` and `createdAt_Lt` filters to more friendly `createdBefore` and `createdAfter`.

✏️ Rename datetime filters

---

docker-compose.yml

This updates the port mounted by docker to `5002` which is consistent with the data-stack port assigned.

🔧 Update port for study creator

---

creator/projects/models.py
creator/projects/schema.py
creator/schema.py
tests/projects/test_update_project.py

Adds `updateProject` mutation to update fields on existing projects.
Currently only supports the `workflow_type` and `project_type` fields for update. Other fields may require direct communication with Cavatica.
Also adds a new research project type.
Closes #297 
Closes #299

✨ Add updateProject mutation

---

CHANGELOG.md

Feature Emojis: ✨x5 🔧x2 📝x1
Feature Labels: [feature](https://api.github.com/repos/kids-first/kf-api-study-creator/labels/feature) x5 [devops](https://api.github.com/repos/kids-first/kf-api-study-creator/labels/devops) x3 [documentation](https://api.github.com/repos/kids-first/kf-api-study-creator/labels/documentation) x1 [refactor](https://api.github.com/repos/kids-first/kf-api-study-creator/labels/refactor) x1
- (#306) ✨ Add updateProject mutation - @dankolbman
- (#304) 📝 Add page on Data Service settings - @dankolbman
- (#300) ✨ Integrate bucketservice - @dankolbman
- (#302) Terraform 0.12 Upgrade - @blackdenc
- (#296) 🔧 Update port for study creator - @dankolbman
- (#298) 🔧 Load database creds from S3 - @dankolbman
- (#294) ✨ Make bucket modifiable - @dankolbman
- (#293) ✨ Mark …

🏷 Release 1.7.0

---

CHANGELOG.md

Hot fix to un-delete studies that have reappeared in dataservice and stop trying to configure Cavatica projects' type on sync.
Feature Emojis: ♻️x2
Feature Labels: [refactor](https://api.github.com/repos/kids-first/kf-api-study-creator/labels/refactor) x1
- (#308) ♻️ Don't set project type based on project name - @dankolbman
- (#309) ♻️ Un-delete studies that have reappeared - @dankolbman

🏷 Release 1.7.1

---

creator/users/schema.py
tests/users/test_profile.py

Bug:
Can only set email/slack notify to `True` but cannot set it to `False`
Reason:
```
if kwargs.get("slack_notify"): <--- Here is FALSE when try to set slack_notify to FALSE
user.slack_notify = kwargs.get("slack_notify") <--- Then this line is not excuted
```
Fix:
```
if "slack_notify" in kwargs: <--- Check if kwargs has key "slack_notify"
user.slack_notify = kwargs.get("slack_notify")
```

🐛 Fix the user email/slack notify toggle mutation

---

Dockerfile

Installs psql client in base image so that the image uploaded to repos may be used in dev contexts.

🐳 Install postgres in base image

---

requirements.txt

The version of psycopg2 we were using seems to be incompatible with python 3.8.
Bumping to the latest fixed the install issue for me when running with python 3.8.1.

⬆️ Bump psycopg2 to 2.8.4

---

creator/schema.py
creator/studies/schema.py
tests/events/test_studies.py
tests/studies/test_collaborators.py
tests/studies/test_create_study.py
tests/studies/test_update_study.py

Removes the ability to add collaborators through study update mutations instead opting for use of individual add and remove collaborator mutations. Collaborators may still be specified in the create study mutation.

♻️ Refactor collaborator mutations

---

creator/files/schema/file.py
tests/files/test_update_files.py

Allows file tags to be updated with empty arrays.

🐛 Allow files to be updated with no tags

---

creator/files/schema/file.py
creator/files/schema/version.py
tests/files/test_downloads.py

Hard-codes the https schema for download urls.
The request context was coming off the proxy after the ssl had already been terminated making it incorrectly set it as http.
Closes kids-first/kf-ui-data-tracker#575

♻️ Hard-code https scheme for downloads

---

creator/files/management/commands/fakefiles.py
creator/studies/management/commands/fakestudies.py

Sets the random number generator to a static string so that the data created by the `fakestudies` and `fakefiles` commands results in the same data being created.

🔧 Use static seed when creating fake data

---

creator/buckets/factories.py
creator/files/factories.py
creator/studies/factories.py
creator/studies/management/commands/fakestudies.py
creator/users/factories.py
tests/dev/test_reset_db.py

Makes factory boy ignore objects when they already exist so that the application image does not fail when it tries to restart with an existing database.
Also adds a SD_ME0WME0W study to the testuser's studies by default.

✨ Idempotent factories

---

docker-compose.coordinator.yml
docker-compose.yml
docs/development/quickstart.rst

Adds the Release Coordinator as an additional service that may be specified when starting with compose:
```
DEVELOP=True \
DEVELOPMENT_ENDPOINTS=True \
docker-compose \
-f docker-compose.yml \
-f docker-compose.dataservice.yml \
-f docker-compose.coordinator.yml \
up -d
```

🐋 Add coordinator service

---

creator/files/factories.py
creator/files/management/commands/fakefiles.py

- Resets counters for files and versions before command run
- Sorts sets for tags to ensure the same ordering before selecting elements

🐛 Make fake data reproducible

---

CHANGELOG.md

Overhaul of user permissions.
Feature Emojis: ✨x5 🔒x5 🐛x3 ♻️x2 🐋x1 📝x1 🐳x1 🔧x1
Feature Labels: [feature](https://api.github.com/repos/kids-first/kf-api-study-creator/labels/feature) x10 [bug](https://api.github.com/repos/kids-first/kf-api-study-creator/labels/bug) x5 [refactor](https://api.github.com/repos/kids-first/kf-api-study-creator/labels/refactor) x5 [devops](https://api.github.com/repos/kids-first/kf-api-study-creator/labels/devops) x2 [documentation](https://api.github.com/repos/kids-first/kf-api-study-creator/labels/documentation) x2
- (#389) 🐛 Make fake data reproducible - @dankolbman
- (#382) ✨ Idempotent test files - @dankolbman
- (#381) ♻️ Refactor the permission checking for uploading version - @XuTheBunny
- (#379) 🐋 Add coordinator service - @dankolbman
- (#378) 🐛 Create …

🏷 Release 1.9.0

---

dev-requirements.txt

Uses https rather than ssh to install the codecov dependency.

🐛 Use https for codecov

---

creator/settings/development.py
creator/settings/production.py
creator/settings/testing.py
docs/cavatica.rst
tests/events/test_studies.py
tests/projects/test_cavatica.py

For not creating any default Cavatica projects for new studies, set the env to be:
`CAVATICA_DEFAULT_WORKFLOWS=""`
Adding default Cavatica projects for new studies, set the env to be:
`CAVATICA_DEFAULT_WORKFLOWS="workflow1 workflow2"`
Ref https://github.com/kids-first/kf-ui-data-tracker/issues/768

🔥 Remove default Cavatica projects for new studies

---

creator/slack.py

The link for view document
`https://kf-ui-data-tracker.kidsfirstdrc.org/study/SD_NMVV8A1Y/documents/%7Bfile_id%7D?utm_source=slack_daily_dm`
Now change to 
`https://kf-ui-data-tracker.kidsfirstdrc.org/study/SD_NMVV8A1Y/documents/SF_DTE9C0W6?utm_source=slack_daily_dm`
Close #432

🐛 Fix file link in slack updates

---

creator/referral_tokens/schema.py

🐛 Fix referral token event message with f-string

---

creator/files/schema/file.py

✨ Specify what change was made to a document in event message

---

creator/settings/production.py

Gives more time to tasks that tend to take a while.
Closes #441

🔧 Increase task queue timeouts

---

tests/test_fields.py
tests/test_models.py

Adds general tests for models.

✅ Add test for model strings

---

creator/files/views.py

Checks user's permissions for `view_my_version` to see if they may download files for their studies rather than only checking if they may download any file.

🐛 Check view_my_version permissions for downloads

---

creator/files/models.py
creator/files/mutations/file.py
creator/files/nodes/file.py
creator/files/nodes/version.py
tests/conftest.py
tests/data/SD_ME0WME0W/s3_scrape.csv
tests/events/test_files.py
tests/files/test_create_file.py
tests/files/test_file_type_validation.py
tests/files/test_update_files.py
tests/files/test_valid_types.py

Adds a `valid_types` to documents and versions to provide users an easy way to know what file_types may be chosen from.
Closes #462

✨ Valid types field

---

creator/referral_tokens/mutations.py
creator/urls.py

Catches UUID exceptions coming from trying to decode invalid UUIDs and increases the specificity of the general validation error formatting.

🐛 Fix referral token exceptions

---

creator/files/models.py

If there are column names that are non string, like numbers, the current method will fail to parse because `isprintable()` is a string method.

🐛 Stringify before checking for printable chars

---

.circleci/config.yml
creator/management/commands/startresource.py
resource-template/resource/models.py
resource-template/resource/mutations.py
resource-template/resource/nodes.py
resource-template/resource/queries.py
resource-template/tests/test_mutations.py
resource-template/tests/test_queries.py

I needed to make a couple changes in the templates and the template generation code in order to get the tests to pass.
1. Use lower/upper camel casing in test query/mutation templates
- Can't use Python's str.title() method because it doesn't turn snake case into proper camel case (e.g. ingest_request -> Ingest_Request)
2. Change permission codenames referenced in the code to match what gets generated in the db
- When django creates permissions, it uses the lower cased version of the model name (e.g. list_all_ingestrequest)

🐛 Fix startresource command

---

creator/utils.py
requirements.txt
tests/test_utils.py

Makes use of the new `send_kill_horse_command` to kill a job via job id
NOTE: This will likely go away once https://github.com/rq/rq/issues/1371 is implemented.

✨ Kill rq jobs by id

---

dev-requirements.txt
tests/studies/test_create_study.py
tests/studies/test_update_study.py

Removes hypothesis as it was causing unreproducible errors in tests and wasn't being used in any new tests.

🔥 Remove hypothesis testing

---

creator/files/models.py
creator/files/nodes/version.py

Does not resolve the `downloadUrl` for a version unless there is enough information to build it.

🐛 Don't resolve downloadUrls if not enough info

---

creator/email/templates/base.html

Removes the Kids First image from emails in attempt to avoid going to user's spam folder.

🔥 Remove image from email

---

creator/extract_configs/templates/s3_scrape_config.py

The DATA_TYPES should all point to standard concepts instead of being hard coded.

🔧 Point s3_scrape template DATA_TYPES to concepts

---

creator/extract_configs/templates/s3_scrape_config.py

https://docs.python.org/3.8/library/os.path.html says
```
Note: Since different operating systems have different path name
conventions, there are several versions of this module in the standard
library. The os.path module is always the path module suitable for the
operating system Python is running on, and therefore usable for local
paths.
```
But since no other path methods are being used and S3 keys aren't really file paths anyway, it seems reasonable to just split on "/" instead of invoking os.posixpath.
I made a def instead of just a lambda because the filename is often useful for other extract operations as well.

🐛 Don't use os.path.split on S3 keys

---

creator/extract_configs/templates/s3_scrape_config.py

`lambda x: foo(x)` should be the same as `foo(x)` if foo doesn't depend on state

♻️ Remove unnecessary forwarding lambdas

---

manage.py
requirements.txt

This removes the dotenv package as we removed the .env from the repo and strictly set everything through the environment in our entrypoint scripts.
It may be worth transitioning to django-environ at a different time.

🔥 Remove dotenv

---

creator/decorators.py

Prevents a task from failing if an existing log file cannot be found.

🔈 Warn when log file not found

---

creator/decorators.py

Catches any exception when trying to read or write logs to ensure that saving logs does not interfere with the wrapped function.

🔈 Make log IO errors less strict

---

creator/middleware.py
tests/authentication/test_middleware.py
tests/conftest.py

Don't raise errors when the user's auth fails.

🔇 Lower verbosity of auth errors

---

creator/management/commands/schedule_jobs.py

Tries to remove the `inventories_sync` job that was never released into production but is still running in dev and qa.

🔧 Try to remove old job on start up

---

creator/settings/production.py

Ignores GraphQLError exception types in sentry as these exceptions are often used to raise intended errors to the user.

🔇 Ignore GraphQLError in sentry

---

.github/workflows/gh_release.yml

Tells sentry when we make a new release so we can identify when we introduce new errors.

🔧 Notify sentry of releases

---

creator/settings/development.py
creator/settings/testing.py

Sets `DEFAULT_FROM_EMAIL` for dev and testing environments so that email functionality will work correctly when using `send_mail()`.

✉️ Set default from address for tests

---

creator/jobs/schema.py

Allows JobLogs to be filtered by the Job they belong to and the time they were created.

✨ Add more filters for JobLog

---

creator/jobs/models.py
tests/jobs/test_models.py

Sometimes redis returns `None` for scheduled tasks which cannot be converted to DateTime. These fields eventually come back, perhaps after `schedule_jobs.py` is run again, so this just handles the odd occurrences where the scheduler doesn't return a value.

🐛 Handle cases where redis scheduler returns None

---

creator/referral_tokens/mutations.py
tests/referral_tokens/test_new_referral_token.py

Only returns the 'Waiting for user response' if there is a current _valid_ token in existence for the given email. This allows followup invites to be sent out if the original was allowed to expire.
Closes #555

♻️ Only block new tokens if there is an open invite

---

creator/settings/production.py
creator/urls.py
creator/views.py

Splits up the `/graphql` transactions by individual operations to help discern how individual queries are performing.
Ignores `/health_check` transactions.
Closes #559

🔊 Rename Sentry transactions with operation name

---

creator/settings/production.py

Sometimes the sampling context won't have everything we need to filter out web requests (like when a task is running). This checks to make sure the right properties exist before filtering.
Also attempts to convert the environment variable for trace sampling rate to a number and will fallback on a hardcoded default if it cannot.

🐛 Add safeguards for trace sampler

---

creator/releases/models.py

The SBG task service does not respond with a release_id, only a task_id. We should only verify the release_id if it is present.

🐛 Only verify release id if its in the response

---

creator/releases/slack.py

Adds utm tracking to release messages.
Reorganizes message contents.
Makes status updates navigable to release page.
Closes #565 
Closes #554

💄 Clean up release messages

---

Dockerfile
JenkinsfileWorker
bin/dev_entrypoint.sh
bin/dev_worker.sh
bin/entrypoint.sh
bin/scheduler.conf

Tested locally with docker-compose on the ingest-app branch. Ran the start ingest run mutation and the worker looks like it picks up the job and executes successfully.

🐛 Fix bugs from switching to Debian image

---

creator/status/settings/nodes.py
creator/status/settings/queries.py

Adds more settings to the status schema:
- `DATA_TRACKER_URL`
- `DEFAULT_FROM_EMAIL`
- `REFERRAL_TOKEN_EXPIRATION_DAYS`
- `STUDY_BUCKETS_REPLICATION_ROLE`
- `SLACK_RELEASE_CHANNEL`
Moves the `DEVELOPMENT_ENDPOINTS` from settings to features
Closes #568 
Closes #569 
Closes #570

🔧 Add settings to status schema

---

creator/buckets/buckets.py
creator/settings/features.py
creator/status/settings/nodes.py
creator/status/settings/queries.py
tests/buckets/test_buckets.py

Allows configuration of whether or not to create DR buckets for new study buckets.

🔧 Add flag to enabled/disable DR bucket creation

---

JenkinsfileWorker

🔥 Remove build_environments for worker

---

creator/analyses/analyzer.py
tests/analyses/test_extract_data.py

Adds missing import and a test to hit a missing logic branch.
Closes #583

🐛 Add missing import

---

creator/settings/production.py

Increases the time out so that Cavatica sync tasks have time to complete.
Closes #593

🔧 Increase timeout for Cavatica tasks

---

creator/releases/slack.py
creator/slack.py
requirements.txt
tests/tasks/test_slack_notify_task.py

Replaces the deprecated `channels.join` method with `conversations.list` and `conversations.join` and upgrades the slack client to the new slack_sdk distribution.
Closes #590

⬆️ Upgrade slack sdk

---

.github/workflows/gh_release.yml
.github/workflows/sentry.yml

Makes the Sentry action only run on tagged release commits and ignores issues when no commits are found.

👷 Add new workflow for sentry releases

---

creator/files/nodes/file.py
creator/files/nodes/version.py
creator/jobs/schema.py
tests/files/test_downloads.py
tests/jobs/test_job_downloads.py

Allow developers running the study creator locally to test and use the `/download` endpoint. This is done by checking
if the `DEVELOP` setting is `True`. If so, return `http://` instead of `https://` in the download URLs.
Closes #585.

✨ Set download endpoints to use http in dev mode

---

CHANGELOG.md

- Emojis: 🔥 x1, ⬆️ x1, ✨ x2
- Categories: Removals x1, Ops x1, Additions x2
- [#610](https://github.com/kids-first/kf-api-study-creator/pull/610) - 🔥 Remove lingering ego auth fields - [f091a41a](https://github.com/kids-first/kf-api-study-creator/commit/f091a41a7de66f086b7240025eaaf6186655bf3d) by [dankolbman](https://github.com/dankolbman)
- [#606](https://github.com/kids-first/kf-api-study-creator/pull/606) - ⬆️ Bump django from 2.2.13 to 2.2.18 - [8ef82bd7](https://github.com/kids-first/kf-api-study-creator/commit/8ef82bd73dc61e1498f358fd2b482582c8862cdd) by [dependabot[bot]](https://github.com/apps/dependabot)
- [#601](https://github.com/kids-first/kf-api-study-creator/pull/601) - ✨ Make events in data_review node sortable with EventFilter - …

🏷 Release 1.16.0

---

creator/authentication.py
tests/authentication/test_client_credentials_auth.py

The `get_tokens(aud)` is always evaluated even if the key is already in the cache. This results in new tokens being fetched every time the `client_headers` function is called even though they only need to be generated if they are not yet in the cache.

🐛 Don't refetch tokens every request

---

requirements.txt

Upgrades Sentry to [1.0.0](https://github.com/getsentry/sentry-python/releases/tag/1.0.0).

⬆️ Upgrade Sentry sdk

---

creator/schema.py
creator/settings/development.py
tests/test_debug_middleware.py

Adds a `_debug` field in the query schema so that we may see raw sql executed for each query.
This middleware is only added for the development settings and requires `DEBUG = True` to be added to the schema.
**Example:**
```
query Study {
_debug {
sql {
rawSql
duration
}
}
status {
name
version
commit
queues
}
}
```

✨ Add debug middleware

---

creator/tasks.py
tests/tasks/test_analyze_task.py

Logs a warning message instead of raising an exception when one or more errors are encountered when analyzing files.
This avoids trackbacks in logs and errors appearing on Sentry when documents fail analysis.

🔊 Warn instead of raising exception

---

creator/decorators.py

Closes #603.
Refactors the task decorator logs to be less repetitive.

♻️ Condense status check logs

---

.gitignore
creator/ingest_runs/genomic_data_loader.py
creator/ingest_runs/signals.py
creator/ingest_runs/tasks/ingest_run.py
creator/ingest_runs/utils.py
creator/settings/development.py
creator/settings/production.py
creator/settings/testing.py
creator/studies/data_generator/study_generator.py
tests/ingest_runs/test_genomic_data_loader.py
tests/ingest_runs/test_tasks.py
tests/ingest_runs/test_utils.py
tests/integration/fixtures.py

Closes #501 
-   Detect and report missing data
-   What happens when we merge things together and lose records?
-   How do we catch this (use outer merge) and how do we report this
-   Cases - Dataservice is missing specimens, seq experiments
-   Improve error handling
-   Add try/excepts around each load function in ingest_gwo
-   Log the exception and then re-raise to gracefully stop execution of the
ingest gwo
-   Validate ingest_gwo 
- We should add post ingest_gwo validation / sanity check to make sure the right # of entities were loaded
-   Similar to \_assert_load in the study_generator.py
-   Event firing for various important things
- Fire an event at the end of a successful ingest task that contains total counts of entities loaded
- Fire an event when we encounter missing data …

✨ Ingest task genomic workflow output

---

creator/ingest_runs/genomic_data_loader.py
requirements.txt
tests/ingest_runs/test_genomic_data_loader.py

Closes #644.
Recent changes to the ingest library broke two of the GenomicDataLoader tests. These are fixed here, and the version of the ingest library dependency used is upgraded.

♻️ Modify tests for upgraded ingest lib

---

creator/status/banners/mutations.py
tests/status/test_banner_mutations.py

Closes #659 
Adds timezone information to the dates being saved in the Banner mutation and its tests.

♻️ Add timezone to Banner mutation datetimes

---

creator/files/mutations/version.py
creator/settings/production.py
tests/files/test_upload.py

Job logs currently accumulate as Django appends strings to the file names if the file already exists. Job logs are intended to be appended to, so this behavior is unnecessary. We do, however, need to make sure versions do not get overwritten by other versions that share the same name so we need to prepend a uuid.

♻️ Overwrite S3 files when appending

---

.circleci/config.yml

Closes #650 
Cache our dependencies after installing. Check for cached dependencies before installing them.

👷 Cache dependencies in CircleCI

---

creator/schema.py

Add a top level `node` query that can query for and return any node type. Looks like it is built-in to graphene just had to add it to the schema.
```
query {
node(id: "RmlsZU5vZGU6U0ZfMDAwMDAwMDA=") {
... on FileNode {
id
name
}
}
}
```
```
{
"data": {
"node": {
"id": "RmlsZU5vZGU6U0ZfMDAwMDAwMDA=",
"name": "assume.avi"
}
}
```

✨ Add node query for querying nodes

---

.circleci/config.yml
creator/files/nodes/file.py

Closes #648 .
Silences warnings made by graphene_django and markdown during testing. For markdown, updating to Python 3.8 is required.

♻️ Address graphene and markdown warnings

---

creator/buckets/migrations/0003_add_organizations.py
creator/events/migrations/0019_add_organizations.py
creator/referral_tokens/migrations/0002_add_organizations.py

Tested in deployed dev environment with the following steps:
1. Undo add organization migrations for: buckets, referral_tokens, events, studies, and organizations
2. Run new migrations
3. Check that the Default Organization was created, and existing buckets, referral_tokens and studies are linked to the Default Organization

🐛 Fix order of organization migrations

---

creator/settings/development.py
creator/settings/production.py
creator/settings/testing.py

Bumps the connection limit to 250 to allow single queries to return more relations.
Closes #691

🔧 Increase max number of relay connections

---

bin/entrypoint.sh

Supervisor seems to be terminating the scheduler for unspecified reasons. This runs the scheduler directly in the shell.

🔧 Run scheduler without supervisor

---

creator/data_templates/mutations/study_templates.py
creator/data_templates/mutations/template_version.py
creator/data_templates/schema.py
tests/data_templates/test_study_template_mutations.py
tests/data_templates/test_template_version_mutations.py

Closes #676 
Adds mutations to assign or un-assign template versions to studies for use by data submitters, along with appropriate tests. The mutations take a list of studies and a list of template_versions as input, then adds or removes the provided studies from each of the provided template_versions. A `success` Boolean is returned, along with a list `studies` of the studies invoked, and finally the resultant `template_versions`.
`addTemplatesToStudiesMutation`:
`removeTemplatesFromMutation`:

✨Add mutations to link/unlink templates to/from studies

---

creator/analyses/file_types.py
creator/extract_configs/templates/aliquot_manifest_config.py
creator/extract_configs/templates/biobank_manifest_config.py
creator/extract_configs/templates/biospecimen_collection_manifest_config.py
creator/extract_configs/templates/general_observations_config.py
creator/extract_configs/templates/participant_config.py
creator/extract_configs/templates/participant_diseases_config.py
creator/extract_configs/templates/participant_phenotypes_config.py
creator/extract_configs/templates/sequencing_manifest_config.py

Right now an expedited type includes all columns as required. Reduce the required columns for each expedited file type to a subset of columns that covers what is required by Data Service and also includes fields that may not be required by Data Service but are fields we want to capture anyway (e.g. Proband).
Closes #702

♻️ Relax required columns in file types

---

creator/organizations/nodes.py
tests/organizations/test_organizations_queries.py

Closes #707 
Adds a users field to Organization queries so that one can see which users are members of an organization in query results.

✨ Create users subquery for Organization queries

---

creator/organizations/mutations.py
creator/organizations/queries.py
creator/users/queries.py
creator/users/schema.py
tests/users/test_queries.py

Closes #700 
Add the ability to filter users by organization in the `allUsers` query. An organization node ID is supplied as input to the query and all users that are a member of that organization are returned.

✨ Add User organization filter

---

creator/settings/development.py
creator/settings/production.py

We're using Sentry in the new DeWrangle app.
Unfortunately we've been encountering some CORS related errors:
- https://github.com/kids-first/dewrangle/pull/26/files#diff-882b2c04b01b2e8b2cdcf1817c30ea503a8005f1c0d54cfff37053b6801fea85R29-R33
Sentry uses the `sentry-trace` header to correlate issues across the front and back end pieces of an application:
- https://develop.sentry.dev/sdk/performance/#header-sentry-trace
Since this is a non-standard header we need to configure the CORS middleware to allow it:
- https://pypi.org/project/django-cors-headers/
I've made this change for both local development, and production, since Sentry is expected to work in both.

🛠 add 'sentry-trace' to CORS allowed headers

---

creator/settings/production.py

Configures the TaskLogger directly in the top logging configuration to ensure that task logs are produced and stored.
This is not desired long-term as it will send these logs directly to stdout which will get captured in the cloudwatch logs for the application. This will result in a lot of doubly-stored and unnecessary cruft going into places like cloudwatch and s3.

🔊 Configure TaskLogger directly

---

creator/groups.py
tests/data_templates/test_data_templates_queries.py

Currently only the Administrators role has permission to view and list templates. This adds view/list template permissions to all of the non-machine groups/permission roles

🐛 Permit all non-machine roles to view and list templates

---

creator/data_templates/signals.py

Closes #737.
Incorporate the user into the template event description like in the other file events. As far as I can tell, it works exactly the same here.

💬 Add user to template event description

---

creator/data_templates/packaging.py
creator/data_templates/views.py
creator/urls.py
tests/data_templates/test_download_templates.py
tests/data_templates/test_package_templates.py

Closes #727 
Adds a download endpoint from the template admin view on DataTracker to download any set of templates. Right now only templates within a single study can be downloaded in one request, which is not convenient for admins.

✨ Add endpoint to download template versions

---

creator/ingest_runs/tasks/validation_run.py
tests/ingest_runs/test_validation.py

Closes #723 
Removes dependence on hardcoded ExtractConfigs to run validation. Validation now uses templates to map source file columns to standard concepts rather than ExtractConfigs.

♻️ Refactor validation to use templates

---

creator/settings/production.py

Configures the logging for release tasks/jobs so that log statements make it to stdout. This is might not the long term solution since we don't necessarily want to have to configure logging for each individual module. But it is an important fix that will help us debug release issues until we figure out the longer term solution for API logging.

🔊 Configure release task logging directly

---

creator/ingest_runs/tasks/validation_run.py
creator/ingest_runs/views.py
tests/ingest_runs/test_validation_result_downloads.py

Closes #762 
Tested in deployed dev and locally.

♻️ Omit Content-Length header in download validation report

---

creator/jobs/models.py
tests/decorators.py

Closes #766 
Django raises a `SuspiciousFileOperation` exception if the API tries to write into the BASE_DIR. We needed to move the local logs directory outside base application directory

🐛  Fix writing of job logs in local development

---

creator/releases/models.py
creator/settings/development.py
creator/settings/production.py
creator/settings/testing.py

Closes #760 
Tested locally and in deployed dev. Now we can see log messages from all loggers under the parent creator logger in the console and the TaskLogger's stream

🐛 Fix API logging

---

creator/settings/features.py
creator/slack.py
tests/tasks/test_slack_notify_task.py

🐛 Fix slack notifications

---

creator/studies/mutations.py
tests/studies/test_create_study.py

The create study mutation first creates a study in Dataservice and then uses the study attributes from the response to create a Study in our db. This fails if there are Dataservice study fields (e.g. short_code, domain) that are not yet on the study creator Study model. This fix ensures that only Dataservice study attributes that exist in the Study model are set.

♻️ Only save study attrs from Dataservice that exist on Study

---

tests/events/test_files.py

Some file event tests randomly fail bc they depend on a user that is not deterministic

🐛 File event tests should be deterministic

---

CHANGELOG.md

- Emojis: 🐛 x3, ♻️ x3, 📌 x1, ✨ x2
- Categories: Additions x2, Fixes x3, Ops x1, Other Changes x3
- [#797](https://github.com/kids-first/kf-api-study-creator/pull/797) - 🐛 File event tests should be deterministic - [e809638b](https://github.com/kids-first/kf-api-study-creator/commit/e809638b5ddc569502aee97fccaacbd7432e2412) by [znatty22](https://github.com/znatty22)
- [#791](https://github.com/kids-first/kf-api-study-creator/pull/791) - 🐛 Use proper bucket arn in bucket inventory configuration - [90455437](https://github.com/kids-first/kf-api-study-creator/commit/904554379c9e43fc2473600cdff3890b5e191b27) by [znatty22](https://github.com/znatty22)
- [#794](https://github.com/kids-first/kf-api-study-creator/pull/794) - ♻️ Only save study attrs from Dataservice that exist on Study - …

🏷 Release 1.20.0

---

creator/studies/management/commands/syncstudies.py

A string in the sync studies command file wasn't actually an f-string when it's supposed to be. Fix this and apply black to the file.

🐛 Fix study sync f-string

---

.circleci/config.yml
Dockerfile
creator/studies/dataservice.py
dev-requirements.txt

The API queries the Dataservice when it syncs studies between Dataservice and itself. Unfortunately there is a bug where it only ever requests the first 100 studies since this was maximum # of resources you can fetch in a single request. This is a problem since there are more than 100 studies that need to be synced which causes study search issues on the UI.
- Increase the maximum page size from 100 to 1000 in the sync study task

:bug: Sync all studies in dataservice
